server:
  http:
    addr: 0.0.0.0:8004
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9004
    timeout: 1s

data:
  database:
    driver: postgres
    source: postgres://chat_user:chat_password@postgres:5432/chat_db?sslmode=disable
  redis:
    addr: redis:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

minio:
  endpoint: "minio:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin123"
  bucket: "chat-attachments"
  use_ssl: false

upload:
  max_file_size: 100MB
  allowed_types:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "image/webp"
    - "application/pdf"
    - "application/msword"
    - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    - "text/plain"
    - "application/zip"
    - "application/x-rar-compressed"

antivirus:
  enabled: false
  clamav_host: "localhost:3310"
