server:
  http:
    addr: 0.0.0.0:8084
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9094
    timeout: 1s

data:
  database:
    driver: postgres
    source: postgres://chat_user:chat_password@localhost:5432/chat_db?sslmode=disable
  redis:
    addr: localhost:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

mqtt:
  broker_url: "tcp://localhost:1883"
  username: "presence_service"
  password: "presence_service_password"
