server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s

data:
  database:
    driver: postgres
    source: postgres://chat_user:chat_password@localhost:5432/chat_db?sslmode=disable
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

mqtt:
  broker_url: "tcp://localhost:1883"
  username: "message_service"
  password: "message_service_password"
  topics:
    - "chat/+/messages"
    - "chat/+/typing"

auth:
  service_url: "http://localhost:8000"
