server:
  http:
    addr: 0.0.0.0:8003
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9003
    timeout: 1s

data:
  database:
    driver: postgres
    source: postgres://chat_user:chat_password@postgres:5432/chat_db?sslmode=disable
  redis:
    addr: redis:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

services:
  auth_service: "http://auth-service:8000"
  message_service: "http://message-service:8001"
  presence_service: "http://presence-service:8002"
  media_service: "http://media-service:8004"

mqtt:
  broker_url: "tcp://emqx:1883"
  username: "chat_api"
  password: "chat_api_password"
